### ISSUE TITLE
Overall Progress Bars is broken

### ISSUE THREAD

**Issue by Kumirei** [Kumirei/Userscripts#21]
https://community.wanikani.com/t/userscript-overall-progress-bars/56208/60

**Comment by lupomikti** [comment]
Oh I'll take a look at this over the weekend if I have some time. I see that a solution was posted in the thread but I'd like to take this moment to update it to use the CSS variables as well (I'll see if I can make it work like "Default: completely up to variables; Breeze: hardcoded for original Breeze Dark" because Breeze Dark 2 uses the variables and there would be no need for a switch for it.

Oh and I think this is a duplicate of #11 but I'll let you choose to close this one or not.

**Comment by Kumirei** [comment]
Oops, it is indeed a duplicate. You don't have to look into it by any means, this is mainly a note to myself to look at it whenever I get the time to do some scripting
